# Generated by Django 5.0.6 on 2024-05-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("contributors", models.TextField()),
                ("date", models.CharField(max_length=20)),
                ("place_origin", models.CharField(max_length=50)),
                ("publisher", models.CharField(max_length=50)),
                ("language", models.CharField(max_length=20)),
                ("notes", models.TextField()),
            ],
        ),
    ]
