# Generated by Django 5.0.6 on 2024-06-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookcat", "0002_remove_book_title_book_call_num_book_genre_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="subject",
            new_name="category",
        ),
        migrations.AddField(
            model_name="book",
            name="BM_cat",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="barcode",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="loc_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
