# Generated by Django 5.0.7 on 2024-07-13 00:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookcat", "0004_alter_book_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="image_loc",
        ),
    ]
