# Generated by Django 5.0.7 on 2024-07-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookcat", "0005_remove_book_image_loc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="BM_cat",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="barcode",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="language",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="book",
            name="loc_code",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
